language: c

before_install:
  - rm -rf ~/.nvm
  - wget https://raw.githubusercontent.com/visionmedia/n/master/bin/n -qO n
  - chmod +x n
  - sudo cp n /usr/local/bin/n
  - sudo chmod -R a+xw /usr/local
  - n --version

script:
  - n 0.10
  - node -v; which node; npm -v; which npm
  - JOBS=max npm install
  - npm test && rm -rf node_modules/

  - n latest
  - node -v; which node; npm -v; which npm
  - JOBS=max npm install
  - npm test && rm -rf node_modules/

  - n io latest
  - iojs -v; which iojs; npm -v; which npm
  - JOBS=max npm install
  - npm test

notifications:
  email:
    - rod@vagg.org
    - ralphtheninja@riseup.net
